// generated by TSEMBIND

// define type aliases for various native number types
type Char = number;
type SignedChar = number;
type UnsignedChar = number;
type Short = number;
type UnsignedShort = number;
type Int = number;
type UnsignedInt = number;
type Long = number;
type UnsignedLong = number;
type Float = number;
type Double = number;


export class xClass {
constructor(arg0: Int, arg1: string);
	
	incrementX(): void;
	
	static getStringValue(arg0: xClass): string;
	
	static PrintNum(): void;
	x: Int
	anh: undefined
	delete(): void;
}
export interface CustomEmbindModule {
	xClass: typeof xClass
}
declare function factory(): Promise<CustomEmbindModule>;
export default factory;
